"""initial schema

Revision ID: 0e5b85073a7b
Revises: 
Create Date: 2026-05-08 22:13:41.872878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='CNY', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.String(length=64), server_default='read,write', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('merchant_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_kind', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchant_rules_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rules'))
    )
    op.create_index('ix_merchant_rules_user_priority', 'merchant_rules', ['user_id', 'priority'], unique=False)
    op.create_table('statement_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_row_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('deduped_count', sa.Integer(), nullable=False),
    sa.Column('classified_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_statement_imports_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_statement_imports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_imports')),
    sa.UniqueConstraint('file_hash', name=op.f('uq_statement_imports_file_hash'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_import_id', sa.Integer(), nullable=True),
    sa.Column('tx_kind', sa.String(length=16), nullable=False),
    sa.Column('tx_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='CNY', nullable=False),
    sa.Column('amount_settled_cny', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('merchant_raw', sa.String(length=255), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=True),
    sa.Column('counterparty_raw', sa.String(length=255), nullable=True),
    sa.Column('description_raw', sa.String(length=512), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_tx_id', sa.String(length=128), nullable=True),
    sa.Column('external_merchant_id', sa.String(length=128), nullable=True),
    sa.Column('payment_method_raw', sa.String(length=128), nullable=True),
    sa.Column('is_mirror', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mirror_of_id', sa.Integer(), nullable=True),
    sa.Column('source_unique_key', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mirror_of_id'], ['transactions.id'], name=op.f('fk_transactions_mirror_of_id_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_import_id'], ['statement_imports.id'], name=op.f('fk_transactions_statement_import_id_statement_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('source_unique_key', name=op.f('uq_transactions_source_unique_key'))
    )
    op.create_index('ix_transactions_user_account_time', 'transactions', ['user_id', 'account_id', 'tx_time'], unique=False)
    op.create_index('ix_transactions_user_merchant_norm', 'transactions', ['user_id', 'merchant_normalized'], unique=False)
    op.create_index('ix_transactions_user_tx_time', 'transactions', ['user_id', 'tx_time'], unique=False)
    op.create_table('dedup_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_tx_id', sa.Integer(), nullable=False),
    sa.Column('mirror_tx_id', sa.Integer(), nullable=False),
    sa.Column('match_kind', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mirror_tx_id'], ['transactions.id'], name=op.f('fk_dedup_candidates_mirror_tx_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_tx_id'], ['transactions.id'], name=op.f('fk_dedup_candidates_primary_tx_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dedup_candidates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedup_candidates'))
    )
    op.create_index('ix_dedup_user_status', 'dedup_candidates', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dedup_user_status', table_name='dedup_candidates')
    op.drop_table('dedup_candidates')
    op.drop_index('ix_transactions_user_tx_time', table_name='transactions')
    op.drop_index('ix_transactions_user_merchant_norm', table_name='transactions')
    op.drop_index('ix_transactions_user_account_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('statement_imports')
    op.drop_index('ix_merchant_rules_user_priority', table_name='merchant_rules')
    op.drop_table('merchant_rules')
    op.drop_table('categories')
    op.drop_table('api_tokens')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
